set -g default-terminal "screen-256color"

# Use Ctrl+A as the prefix key
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# Automatically set window title
setw -g automatic-rename

# Use Vim shortcuts
setw -g mode-keys vi

# Highlight active window
# set-window-option -g window-status-current-bg blue

# Set window notifications
setw -g monitor-activity on
set -g visual-activity on

# shell
set-option -g default-shell /bin/zsh

# enable scroll
set -g mouse on
