set -g default-terminal "screen-256color"
unbind-key C-b
set -g prefix C-a
bind-key C-a send-prefix

# Automatically set window title
setw -g automatic-rename

# Highlight active window
# set-window-option -g window-status-current-bg blue

# Set window notifications
setw -g monitor-activity on
set -g visual-activity on

# shell
set-option -g default-shell /bin/zsh

# enable scroll
set -g mouse on
