# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  default:
    desc: Print a greeting message
    cmds:
      - echo "{{.GREETING}}"
    silent: true

#  from-home:
#    cmds:
#      - pwd
#
#  from-working-directory:
#    dir: '{{.USER_WORKING_DIR}}'
#    cmds:
#      - pwd
